repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args:
    - --autofix
    - --indent=4
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.51.0
  hooks:
  - id: eslint
    types: [file]
    types_or: [javascript, ts]
    additional_dependencies:
    - '@typescript-eslint/eslint-plugin@6.7.5'
    - '@typescript-eslint/parser@6.7.5'
    - eslint@8.51.0
    - eslint-config-standard-with-typescript@39.1.1
    - eslint-plugin-import@2.28.1
    - eslint-plugin-n@16.1.0
    - eslint-plugin-promise@6.1.1
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.3
  hooks:
  - id: prettier
    types: [file]
    types_or: [javascript, ts]
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
  - id: black
    args: [--line-length, '100']
    types: [python]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black]
    types: [python]
